apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-jnodes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: container-bff
          image: luisaniar/jnodes-bff:latest
          ports:
            - containerPort: 8080
        - name: container-front
          image: luisaniar/jnodes-frontend:latest
          ports:
            - containerPort: 3000
