version: '3'
services:
  bff:
    build:
      context: .
      dockerfile: bff/Dockerfile
    image: luisaniar/jnodes-bff
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    image: luisaniar/jnodes-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - bff
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

