# Usa una imagen base de Node.js
FROM node:18

# Crea un directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos package.json y package-lock.json desde la raíz del proyecto
COPY ../package*.json ./

# Instala las dependencias
RUN npm install

# Copia el archivo server.js desde la carpeta bff
COPY ./bff/server.js .

# Expone el puerto 8080
EXPOSE 8080

# Comando para iniciar el servidor
CMD ["node", "server.js"]
